name = input("ENTER YOUR NAME : ")
age = int(input("ENTER YOUR AGE :"))
height = float(input("ENTER YOUR HEIGHT : "))
number = int(input("ENTER YOUR FAVOURTIE NUMBER : "))
year = 2026 - age
print("----------------------------------------------------------")
print("NAME IS " ,name , "TYPE IS :" ,type(name),"& MEMORY ADDRESS : ", id(name))
print("AGE IS " ,age , "TYPE IS :" ,type(age),"& MEMORY ADDRESS : ", id(age))
print("HEIGHT IS " ,height , "TYPE IS :" ,type(height),"& MEMORY ADDRESS : ", id(height))
print("NUMBER IS " ,number , "TYPE IS :" ,type(number),"& MEMORY ADDRESS : ", id(number))
print("----------------------------------------------------------")
print(f"YOUE BIRTH YEAR IS APPROXIMATELY : {year} (BASED ON YOUR AGE OF {age})")

print("----------------------------------------------------------")
print("__________THANK YOUR FOR PROVIDING US YOUR DATA____________")
